name: CI-Pipeline
on: 
  push

jobs:
  name: project-testing
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: python-setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: pipeline-run
      run: |
        dvc repro
